# Generated by Django 2.1.4 on 2018-12-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Полное имя')),
                ('votes', models.IntegerField(verbose_name='Количество голосов')),
            ],
            options={
                'verbose_name_plural': 'Избираемые',
                'verbose_name': 'Избираемый',
            },
        ),
    ]
